 print("\n Youtube Manager  |  Choose a option")
        print("1. List a favourite videos")
        print("2. Add a youtube video")
        print("3. Update a youtube video")
        print("4. Delete a youtube video ")
        print("5. Exit the app")